image: python:3.9

before_script:
  - pip install -r requirements.txt

stages:
  - test

pytest:
  stage: test
  script:
    - pytest --cov=day01/challenge1 --cov-report=xml:coverage.xml
    # Add similar line for other challenges and days.
  artifacts:
    paths:
      - coverage.xml
  coverage: '/TOTAL.* (\d+\%)/'
